sonar.projectKey=DevSecOps_Lab04-FDSI
sonar.organization=https://sonarcloud.io/organizations/juanesgl/projects
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.cfamily.compile-commands=build/compile_commands.json